services:
  ################ Python Producer #################

  python-producer:
    build:
      context: ./python-producer
      dockerfile: Dockerfile
    container_name: python-producer
    environment:
      KAFKA_SERVER: broker:29092
      KAFKA_TOPIC: financial-transactions
    networks:
      - flink-ecommerce-network

  ################ Python Producer #################

networks:
  flink-ecommerce-network:
    name: flink-ecommerce-network
    external: true
